Tests for database group members

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -56,13 +56,13 @@ fi
 shopt -s globstar #This can be used if we wanna do wildcard directory search google it if in doubt
 result=$(exec java -jar hooks/checkstyle-8.8-all.jar -c hooks/google_checkstyle.xml server/src)
 
-#if [[ $result != *WARN* ]] || [[ $result != *ERR* ]] ; then
-#	echo "Audit successful."
-#else
-#	echo $result
-#	echo "Audit failed."
-#	exit 1
-#fi
+if [[ $result != *WARN* ]] && [[ $result != *ERR* ]] ; then
+	echo "Audit successful."
+else
+	echo $result
+	echo "Audit failed."
+	exit 1
+fi
 
 # If there are whitespace errors, print the offending file names and fail.
 #exec git diff-index --check --cached $against --
